### ISSUE TITLE
bug: inconsistent waku store responses

### ISSUE THREAD

**Issue by danisharora099** [waku-org/js-waku#1041]
This is a bug report

## Problem

The tests on the current master (which have previously passed for me locally, and also passed for the CI) are failing for me now locally with inconsistent replies for store queries.

## Proposed Solutions

Unsure. Could possibly be a nwaku bug since nothing changed on js-waku.

## Notes

js-waku version: current master -- commit 50c6ea9ea91b0541a134237cc9f5643c2f12b0e3
environment:
- node version: 16
- npm: 8.x
- nwaku version: 0.13

[js-waku-tests.log](https://github.com/waku-org/js-waku/files/10124603/js-waku-tests.log)

Looking at the nwaku logs for one of the failing tests, for eg the generator test on waku-store:
[nwaku_Waku_Store_Generator.log](https://github.com/waku-org/js-waku/files/10124610/nwaku_Waku_Store_Generator.log)

**Comment by fryorcraken** [comment]
When I had this issue, it was because the messages injected by previous tests were not being cleared when the nwaku node is killed and re-started.

This happens when sqlite is used by nwaku (new in v0.12).

To prevent this, we use the in-memory store option of nwaku, which does not use sqlite but instead a simple in-memory storage. As it's in-memory and not on the filesystem, previous messages are deleted when the node restarts between tests.

This is how we enable the in-memory store:

https://github.com/waku-org/js-waku/blob/50c6ea9ea91b0541a134237cc9f5643c2f12b0e3/packages/tests/src/nwaku.ts#LL167C4-L167C53

`process.env.WAKUNODE2_STORE_MESSAGE_DB_URL = "";`

in the logs attached:

```
DBG 2022-11-30 20:53:15.545+05:30 setting up in-memory waku archive driver   topics="wakunode" tid=6490979 file=wakunode2.nim:179
```

So it seemed it worked

We using an environment variable because NodeJS's `spawn` interface does something weird to the command argument, leading to `--store-message-db-url=""` not being processed correctly by wakunode.

Not sure if this is the same issue for you. I assume that if you run tests in isolation, they work?

Also, doing a `git clean -dfx` in your `nwaku` submodule and re-building it might help? (to remove any sqlite file).

**Comment by fryorcraken** [comment]
Something that could help and we would need to do for https://github.com/waku-org/js-waku/issues/52 anyway is to generate a random content topic for each individual test so that there is no message overlap.

To debug your problem, I'd print the messages returned by the store query to understand where the extra messages come from. Do you have a local node running hte background that spam your test node? or do your test node not forget messages between restart?

Note that CI and my laptop are linux env but you have mac so I wonder if it's related.

**Comment by danisharora099** [comment]
> Also, doing a git clean -dfx in your nwaku submodule and re-building it might help? (to remove any sqlite file).

Wow - this fixed things. 
I'll close the issue for now as it's solved :)
But curious why the sqlite files weren't deleted after we stopped to nodes. 🤔 

@fryorcraken

**Comment by fryorcraken** [comment]
> But curious why the sqlite files weren't deleted after the nodes were stopped.

Because you don't want to clear the whole DB and loose all messages when restarting the nodes. It's expected behaviour.
`
Maybe one question for @LNSD: do messages from the sqlite DB (ie, files hanging around) get loaded even if `--store-message-db-url=""` is set?
