### ISSUE TITLE
Doc site seems down

### ISSUE THREAD

**Issue by richtera** [waku-org/js-waku#1121]

**Comment by danisharora099** [comment]
https://js.waku.guide is online, however, is not up-to-date. 
We are currently updating our documentation. Please refer to https://github.com/waku-org/js-waku-examples for updated examples and syntaxes. 
Thanks for your patience.

@richtera

**Comment by richtera** [comment]
If it's back online that's great. I was just getting timeout errors like the website didn't exist

**Comment by danisharora099** [comment]
> If it's back online that's great. I was just getting timeout errors like the website didn't exist

Does it still timeout for you?

**Comment by richtera** [comment]
It still times out for me, yes

**Comment by fryorcraken** [comment]
Hum. works for me TM. 

@jakubgs are you aware of any issues? Do we host those on GitHub pages? There is no reported incident afaik https://www.githubstatus.com/history

**Comment by richtera** [comment]
This is the url mentioned on GitHub https://docs.wakuconnect.dev/ could it be the wrong one?

**Comment by jakubgs** [comment]
The wakuconned/dappconnect branding is dead. The correct addresses are:

* https://js.waku.org/
* https://examples.waku.org/

And the latter returns 404:

![image](https://user-images.githubusercontent.com/2212681/212861636-1f7e1d3c-f9de-41d8-bd69-8203302d35dd.png)

But that's because this task was never completed, specifically the "Get content for examples.waku.org" task:

* https://github.com/waku-org/js-waku-examples/issues/94

The individual examples are still available, for example: https://examples.waku.org/web-chat/

@fryorcraken do you have any plans to complete it?

**Comment by jakubgs** [comment]
I'm closing this as the website not down.
