### ISSUE TITLE
Websocket connection is lost after 10 minutes and reconnect fails

### ISSUE THREAD

**Issue by agazso** [waku-org/js-waku#1403]
This is a **bug report**

## Problem

I have a [web app](https://github.com/logos-innovation-lab/waku-objects-playground) that uses js-waku. It is a light node and it is connected to an nwaku node (see details below) and after 10 minutes of idle time the connection is lost and cannot recover in Firefox and Chromium.

I tried to start the lightnode with or without `pingKeepAlive` and `relayKeepAlive` but there is no difference.

## Notes

js-waku versions:
```
		"@waku/core": "^0.0.18",
		"@waku/create": "^0.0.13",
		"@waku/interfaces": "^0.0.13",
		"@waku/utils": "^0.0.5",
```
Browser version: Firefox 114 Linux, Chromium 114 Linux
Nodes connected to:
```
Version: statusteam/nim-waku:v0.17.0
Multiaddr: /dns4/REDACTED/tcp/443/wss/p2p/16Uiu2HAm8gXHntr3SB5sde11pavjptaoiqyvwoX3GyEZWKMPiuBu

Config used:

--nat:extip:REDACTED
--tcp-port:60001
--nodekey:REDACTED
--websocket-support:true
--relay:true
--store:true
--store-message-retention-policy:capacity:1000000
--filter:true
--lightpush:true
```

Firefox screenshot:
![Screenshot from 2023-06-13 11-59-39](https://github.com/waku-org/js-waku/assets/230163/eb919557-1387-4672-9cd7-9d0987f76287)

Chromium screenshot:
![Screenshot from 2023-06-13 12-01-42](https://github.com/waku-org/js-waku/assets/230163/2f0e31ec-d07d-44b7-a7a6-9cf0d9405e90)

**Comment by agazso** [comment]
Further investigation lead to this issue in nwaku:
https://github.com/waku-org/nwaku/issues/1797

**Comment by agazso** [comment]
It seems that if the `nwaku` configuration provides an appropriate `--ext-multiaddr` then the `js-waku` is able to reconnect.

I think it would be good if `js-waku` also tried to reconnect to the address that was provided in the `dial` function and not only depend on what the peer node advertises about itself. Otherwise it can lead to issues like this and it is quite difficult to track this problem down in a bigger application, especially that it seems like it is working at first, but 10 minutes later the connection is lost.

**Comment by fryorcraken** [comment]
> I think it would be good if js-waku also tried to reconnect to the address that was provided in the dial function and not only depend on what the peer node advertises about itself.

This is js-libp2p behaviour and it makes sense to have it in an unmanaged peer-to-peer network such as gossipsub.
Especially, while it works because you pass a reachable multiaddress to `dial`, it also mean that the misconfigured/misbehaving nwaku node will not be reachable via any other discovery method.

Hence, the remote node behaviour should be fixed to ensure the advertised multiaddr is valid.

Finally, as stated [here](https://github.com/waku-org/nwaku/issues/1797#issuecomment-1590212793) and [there](https://github.com/waku-org/nwaku/issues/1797#issuecomment-1590855162), js-libp2p dials all known mulitaddr for a node so it should still be able to connect if the remote peer (nwaku) advertised at least one correct multiaddr.

This is the part to be investigated: are any valid/reachable multiaddr being advertised and if so, why does js-waku fail to connect?

**Comment by weboko** [comment]
I managed to repro the issue but I conclude that there is nothing wrong with the way `libp2p` reacts. 
If the correct multiaddr is advertised - it will re-dial correctly, otherwise it will fail as expected. 

Anything I am missing here @fryorcraken ?

![image](https://github.com/waku-org/js-waku/assets/118575614/97e6304f-3639-4e6a-8e1c-0d9d30a30666)

**Comment by fryorcraken** [comment]
The remaining question was:

> This is the part to be investigated: are any valid/reachable multiaddr being advertised and if so, why does js-waku fail to connect?

If you are able to confirm that js-waku correctly re-dials the remote peer upon disconnection then this issue can be closed and the work would only be on nwaku side to ensure that advertised addresses are relevant.

**Comment by weboko** [comment]
As I experimented (see screenshot above) js-waku redials a node every 10 minutes of inactivity. If node advertises correct multiaddr then js-waku do not fail.
