### ISSUE TITLE
Task: Manage RLN membership(s) and keys

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-waku#1600]
This is a **bug report/feature or change request/support request**

## Summary

Ensuring that on all Waku clients publishers can manage RLN membership(s) and keys

## Proposed Solutions

A JSON keyfile is used by nwaku to manage credentials. We need to provide a package, compatible with js-rln (or part of?) to enable import and export of this key file..

We need to also review how we want users to manage their RLN credentials in the browser.
Current proposal is to generate the RLN secret from a web3 wallet signature: sign a passphrase, hash it, use it as a secret.
This does not help the membership id, that needs to be retrieved from the smart contract.

We could provide tools to easily save credentials in local storage with a password.

We could also review the PSE work https://github.com/CryptKeeperZK and whether this can be used for RLN credentials.

## Acceptance Criteria

- [x] 1. implement encrypted KeyStore (features: persistence, import / export, encryption);
- [x] 2. implement FE interface by using prev point (features: simplicity, import / export, rpc or rest to nwaku);

**Comment by fryorcraken** [comment]
@rymnc Do you know if https://github.com/CryptKeeperZK can be used for RLN credentials?

**Comment by rymnc** [comment]
Yes, you can use https://github.com/CryptKeeperZK/rlnjs

**Comment by rymnc** [comment]
but it doesn't export the keystore the same way go-waku and nwaku do, so some effort would be required in that direction

**Comment by rymnc** [comment]
> @rymnc Do you know if https://github.com/CryptKeeperZK can be used for RLN credentials?

the original would be better - https://github.com/rate-limiting-nullifier/rlnjs

**Comment by weboko** [comment]
1. implement encrypted KeyStore (features: persistence, import / export, encryption);
2. implement FE interface by using prev point (features: simplicity, import / export, rpc or rest to nwaku);

(1) For implementing KeyStore worth looking into possibility of extending rlnjs library so that we offload following support. Important to keep in mind that encryption part should be consistent between waku clients. Possible mitigation - making it a configurable parameter or directly implementing in @waku/rln on our side. 

(2) FE should use dotenv approach for easy integration in dockerenvironment. Docker spins nwaku then feeds multiaddr to node.

**Comment by weboko** [comment]
*Weekly update*:
- _achieved_: completed flow up items and main stream of work;
