### ISSUE TITLE
Uncaught (in promise) CodeError: Too many outbound protocol streams for protocol

### ISSUE THREAD

**Issue by agazso** [waku-org/js-waku#1650]
This is a **bug report**

## Problem
After running a while in the browser I see plenty of similar errors (see the attached screenshot) where the protocol is different every few seconds. It is unclear if the error is because js-waku cannot reconnect and this is just a side effect of it or this indicates the real problem, but when I see this no messages can be sent. Basically nothing works until I reload the page.

## Notes

- js-waku version: 0.0.19
- Environment (browser software and version, system software and version): Firefox and Chromium on Linux
- Nodes connected to too (e.g. Status test fleet): private go-waku cluster, latest version

![Screenshot from 2023-10-10 16-56-13](https://github.com/waku-org/js-waku/assets/230163/1b283c84-1e90-4091-bb1d-43f7d5002ea9)

**Comment by weboko** [comment]
Was able to observe myself. Looking into it.

**Comment by weboko** [comment]
Reason why it happens:
- too many `send` requests are made e.g `lightPush.send`

My guess it that in local development environment it happens due to page being reloaded due to changes and no conditions applied on `.send` operation. 

`@waku/sdk@0.0.20` or `@waku/core@0.0.24` are safe agaist this error

**Comment by fryorcraken** [comment]
@weboko do note the error also appeared in `filter`. Are we doing preemptive stream opening for it too?
