### ISSUE TITLE
node.lightPush.send returns __v_isRef not set in Vue

### ISSUE THREAD

**Issue by wolz-CODElife** [waku-org/js-waku#1746]
This is a **bug report**

## Problem
I am trying to send a message in Vue 3, and I keep getting the error `__v_isRef not set`. The suggested solution for me was to make the node.lightPush object reactive, which I did with both `ref` and `reactive` but the error still persists.

Here is my implementation to publish:
```ts
async function publish(sender: string, message: string) {
    if (!wakuNode.value || status.value !== 'connected') await start();

     if (!encoder.value)
	 encoder.value = createEncoder({
              contentTopic: contentTopic.value,
              ephemeral: false,
       	 });

     try {
	await lightpush.value.send(encoder.value, {
	     payload: utf8ToBytes(message),
	     timestamp: new Date(),
	});
     } catch (error) {
	  console.error('Error publishing to Content Topic:', error);
     }
}
```

And here is the error I get:
```
Error publishing to Content Topic: CodeError: __v_isRef not set
    at Object.get (components.ts:140:17)
    at isRef (reactivity.esm-bundler.js:978:20)
    at MutableReactiveHandler.get (reactivity.esm-bundler.js:455:9)
    at get peerStore (base_protocol.ts:44:17)
    at Reflect.get (<anonymous>)
    at MutableReactiveHandler.get (reactivity.esm-bundler.js:445:25)
    at Proxy.getPeers (base_protocol.ts:85:64)
    at Proxy.send (index.ts:113:30)
    at async publish
```

## Proposed Solutions
I think the node.lightPush.send isn't observing the reactiveness well, so that should be revised.

## Notes
- `"@waku/sdk": "^0.0.21"`
- `"vue": "^3.3.4"`
- Arc browser, MacOS Ventura 13.3.1

Here is a link to my app's repository: https://github.com/wolz-CODElife/waku-vue-poll.git

**Comment by weboko** [comment]
Error happens in [here](https://github.com/waku-org/js-waku/blob/e40e084429c5c6afb42850cd6308c44d902d9456/packages/core/src/lib/base_protocol.ts#L51)

I advice you to keep `node` in reactive variable instead on `lightpush` or `filter` as because reactive var uses proxies underneath - lightpush object looses references to it's context.

**Comment by wolz-CODElife** [comment]
> I advice you to keep `node` in reactive variable instead on `lightpush` or `filter` as because reactive var uses proxies underneath - lightpush object looses references to it's context.

I already did this(setting only `node` as ref), but it seems there is a compatibility issue with Vue 3.

**Comment by weboko** [comment]
I see this problem is not happening anymore and it seems because you overcame it by [keeping reference to the node outside of Vue](https://github.com/wolz-CODElife/waku-vue-poll/blob/164ea22fd6bb22924a401d5765c800bdb6712892/src/composables/waku.ts#L147) which is a good choice as the node is too complex to be handled by Vue mechanisms.

In that case closing the task.

**Comment by wolz-CODElife** [comment]
Yes, referencing the `WakuNode.lightpush` from top-level eliminate the issue.
