### ISSUE TITLE
update connectionManager.dispatchEvent test to listen to correct events

### ISSUE THREAD

**Issue by fbarbu15** [waku-org/js-waku#1835]
This is a **change request**

## Problem

Update test according to [comment](https://github.com/waku-org/js-waku/issues/1835#issuecomment-1983746362)

**Comment by danisharora099** [comment]
@fbarbu15 can you elaborate? 
What do you aim to achieve?

**Comment by fbarbu15** [comment]
Sure, my aim was to increase test coverage for `waku.connectionManager`
One of the available methods for connectionManager is [waku.connectionManager.dispatchEvent](https://github.com/waku-org/js-waku/blob/master/packages/tests/tests/connection-mananger/methods.spec.ts#L254) and it doesn't works as I would expect (like `waku.libp2p.dispatchEvent`). So if it doesn't work I guess we should either remove it or fix it

**Comment by danisharora099** [comment]
@fbarbu15 upon investigating this, I realise that the test case isn't the right for the API:

you add an event listener `PeersByDiscoveryEvents.PEER_CONNECT_BOOTSTRAP` on `connectionManager` and you dispatch a `peer:connect` event on `connectionManager` as well with bootstrap peer ID.
This is incorrect as the Connection Manager listens on `libp2p` events for `peer:connect`, and not its own's.

Let me draw two scenarios which would be right for this:
1. Connection Manager dispatches and listens to `EPeerByDiscoveryEvents`
2. You listen for `EPeersByDiscoveryEvents.PEER_CONNECT_BOOTSTRAP` and dispatch `peer:connect` even with the bootstrap peer ID through libp2p's event emitter (which ConnectionManager should decode and eventually dispatch `EPeersByDiscoveryEvents.PEER_CONNECT_BOOTSTRAP`

I propose to update this issue description (since this isn't a bug) and change it into an enhancement where we refactor the existing test case & add the above two cases instead.

Moving this to triage while we reach a conclusion & update the issue description.

**Comment by fbarbu15** [comment]
You are correct, now that you explained it, it makes total sense, thank you!
Will update the description and update the test cases.

**Comment by danisharora099** [comment]
resolved by https://github.com/waku-org/js-waku/pull/1897
