### ISSUE TITLE
chore: export `@libp2p/bootstrap` from within `@waku/sdk`

### ISSUE THREAD

**Issue by danisharora099** [waku-org/js-waku#1863]
This is a **bug report**

## Problem

js-waku is released released in interims of ~4 weeks normally. 

During this window, it was found out that `@libp2p/bootstrap` was upgraded by libp2p, which was incompatible with our latest release candidate on npmjs: https://discord.com/channels/1110799176264056863/1211389001920151603/1211662475385245766

## Proposed Solutions

Re-export `@libp2p/bootstrap` from within `@waku/sdk`

## Notes
- Can be added as a peer dependency as well

**Comment by weboko** [comment]
### Problem 

User tries to init a node with:
```ts
const NODE_OPTIONS = {
    libp2p: {
        peerDiscovery: [
            bootstrap({ list: peers }),
        ],
    },
};
```

what doesn't work due t o `bootstrap` from `@libp2p/bootstrap` being of wrong version:

Possible solutions:
1. export `@libp2p/bootstrap` - the best place will be `@waku/discovery` from https://github.com/waku-org/js-waku/issues/1862;
2. lock `@libp2p/bootstrap` version with `peerDependency` to prevent wrong version being used;
3. cover particular need of bootstrapping with list of peers directly without need of extra dependency;

Initially my though was `2` is preferable choice but it was based on the assumption this package is already present. It is optional so due to this I think it might be misleading to have a dependency in `@waku/sdk/package.json` which is not used directly. 

Conceptually `1` to me looks good as it is one of the `discoveries` Waku supports. cc @danisharora099 

For now will:
- define `peerDependency` as temporary measure; 
- provide way to bootstrap with list of `multiaddrs`;

Next steps (blocked by https://github.com/waku-org/js-waku/issues/1862):
- re-export `@libp2p/bootstrap` from `@waku/discovery` so that consumer doesn't need to install `@libp2p/bootstrap`;

Even though I propose this I think it should be only used for advanced cases and preferred way will be to improve configuration options so that there are no extra dependencies or convoluted structure of options passed.

**Comment by danisharora099** [comment]
I was initially in the favour of re-exporting it from `@waku/discovery` (still see pros to it), but as discussed in the PM meeting yesterday, and @fryorcraken's comment here https://discord.com/channels/1110799176264056863/1211676794214944808/1211899679508537344 con I see: it's libp2p's package, so could be misleading to simply re-export it as `@waku/bootstrap`. Simply just locking the version with `peerDependency` on `@waku/sdk` seems better.

In future, we should abstract away libp2p's `peerDiscovery` option and provide `peerDiscovery` as part of Waku options and internally use `bootstrap`

I'd propose to simply add it as a peer dependency for now, and tackle abstracting away discoveries using SDK in a future PR

**Comment by weboko** [comment]
> In future, we should abstract away libp2p's peerDiscovery option and provide peerDiscovery as part of Waku options and internally use bootstrap

exactly what I implement here https://github.com/waku-org/js-waku/pull/1871

next iteration after #1862 is complete will be to add `@libp2p/bootstrap` internally to `@waku/discovery` and export wrapper around it so that it can be used in `@waku/sdk/create.ts` instead of this line: https://github.com/waku-org/js-waku/blob/1355ad31d34c1d3e619e0bee8bc4e1bfdede0b1f/packages/sdk/src/utils/libp2p.ts#L98

**Comment by weboko** [comment]
Once https://github.com/waku-org/js-waku/pull/1871 is merged - the task is locked by https://github.com/waku-org/js-waku/issues/1862
