### ISSUE TITLE
feat(filter)!: limit filter subscriptions to use a single decoder

### ISSUE THREAD

**Issue by adklempner** [waku-org/js-waku#1981]
This is a **bug report/feature request/support request/change request**

## Problem

The subscribe function for filter accepts either a single decoder or an array of decoders. This leads to a lot of overhead for the library consumer when handling the response: it might fail before even attempting a subscription, all subscriptions requests might fail, some might fail and some succeed, or all succeed. It's cleaner for the function to accept a single decoder and respond with a single failure or success.

## Proposed Solutions

Refactor subscribe function in filter to only accept a single decoder

**Comment by weboko** [comment]
This issue proposes a solution to the problem of ambiguity of error handling when we don't have [fail or not fail](https://github.com/waku-org/js-waku/pull/1971#discussion_r1577360518) which happens because of a need to provide support to multiple `decoders`. 

@vpavlin @hackyguru do you think we should continue supporting ability to subscribe to multiple `decoders`?
