### ISSUE TITLE
bug: Filter subscriptions are not stable and missing messages

### ISSUE THREAD

**Issue by weboko** [waku-org/js-waku#2139]
This is a **bug report**

## Problem
- Initial Observations:
   - Stream resets over Mplex causing incoming pipe failures.
   - Compatibility issues prevent upgrading to Yamux, which is better suited for large data transfers.
   - Errors observed: stream reset and buffer overflow.

- Recent Updates:
   - Upgrading to libp2p v2 has been initiated.
   - Mutex locks for protocol peer management are helpful but do not fully resolve issues with Filter and LightPush.
   - Unreliable nodes in the network affect performance, highlighting a need for better node selection and reconnection mechanisms.

- Specific Observations:

   - When it works, Filter and LightPush function correctly, but issues arise intermittently.
   - Two browser instances showed different behaviors: one worked continuously while the other failed after a few sequences.
   - Possible issues with node health and js-waku's ability to find and reconnect to better nodes.

Full report: https://github.com/waku-org/js-waku/issues/2139#issuecomment-2399345230

**Comment by weboko** [comment]
@danisharora099 to update description and share info about the problem and findings

**Comment by danisharora099** [comment]
Updates:

When it works, it works. There is definitely room for improvement in certain aspects, but for the times it doesn't work at all are the weird times. 
Re-summarising my finding from the last few days:
- Sometimes either js-waku or nwaku is causing Stream resets over Mplex which leads to incoming pipe failures
- We can't upgrade to Yamux yet to eliminate that because of an imcompatibility between js-libp2p and nimlibp2p: https://github.com/libp2p/js-libp2p/issues/2505 https://discord.com/channels/864066763682218004/1285880828228009995/1285905326280933388
- Also initiated an upgrade to libp2p v2 to see if there's anything underneath that could help: https://github.com/waku-org/js-waku/pull/2143
- PR with mutex locks for protocol peer management is definitely helpful, especially to keep the state of peers consistent, but I was able to still find myself struggling with Filter subscriptions sometimes. (At least messages missed)  https://github.com/waku-org/js-waku/pull/2137
   - I would agree subjectively did improve things (for objective statistics, I forked the dogfooding app to help -- attaching screenshot) 

> It might be fixed by https://github.com/waku-org/js-waku/pull/2137
Unfortunately not the case. I have been extensively testing the RC with mutex locks, and problems around failures with LightPush and Filter still exist quite a lot. Maybe better, but still a problem.

Yeah, similar observations. When it works, it works. There is definitely room for improvement in certain aspects, but for the times it doesn't work at all are the weird times. 
Re-summarising my finding from the last few days:
- Sometimes either js-waku or nwaku is causing Stream resets over Mplex which leads to incoming pipe failures
- We can't upgrade to Yamux yet to eliminate that because of an imcompatibility between js-libp2p and nimlibp2p: https://github.com/libp2p/js-libp2p/issues/2505 https://discord.com/channels/864066763682218004/1285880828228009995/1285905326280933388
- Also initiated an upgrade to libp2p v2 to see if there's anything underneath that could help: https://github.com/waku-org/js-waku/pull/2143
- PR with mutex locks for protocol peer management is definitely helpful, especially to keep the state of peers consistent, but I was able to still find myself struggling with Filter subscriptions sometimes. (At least messages missed)  https://github.com/waku-org/js-waku/pull/2137
   - I would agree subjectively did improve things (for objective statistics, I forked the dogfooding app to help -- attaching screenshot) 

> It might be fixed by https://github.com/waku-org/js-waku/pull/2137
Unfortunately not the case. I have been extensively testing the RC with mutex locks, and problems around failures with LightPush and Filter still exist quite a lot. Maybe better, but still a problem.

![Image](https://github.com/user-attachments/assets/069632c5-be2d-4a42-9006-30789fe461b4)

-----

Some interesting observation:
I opened two browser instances simultaneously pushing sequences of messages with LP, and receiving with Filter, with a bunch of nodes in their local peer cache. It was seen that on the first window, it kept going. Filter worked. LightPush worked. (Tested until 3 sequences of 10 messages, and running) Not to say that it didn't miss a few messages.
The other tab started to fail with LightPush on the 2nd sequence, and never recevered from it. Filter was still receiving messages sent by the other node (not self's as it wasn't able to push any).
Seems like two problems at hand, or maybe a fusion into one:
- there are unhealthy/unreliable nodes in the network being found
- js-waku should do a better job at finding and reconnecting to better nodes 
   - to be understood if this is js-waku's fault of not doing a good job at finding better nodes, or just no good nodes available

![Image](https://github.com/user-attachments/assets/d4401adc-8498-467b-9ee1-3822388e689b)
![Image](https://github.com/user-attachments/assets/f3d64806-f0d8-470b-ac05-00f02128bfa5)

Few mins later:
- Instance 2 completely couldn't recover with LP and Filter
- Instance 1 gave up with Filter, going strong with LP

![Image](https://github.com/user-attachments/assets/36e61301-baef-494f-b092-d16707316ca4)

**Comment by weboko** [comment]
Reopening since issue is still present but might be fixed by https://github.com/waku-org/js-waku/issues/2158
